import Head from 'next/head';

import { ConnectButton } from '@rainbow-me/rainbowkit';
import { GetGreeter, SetGreeter } from '../components/contract';
import SellOutCheckOut from '@/components/SellOutCheckOut/SellOutCheckOut';
import { useSelloutModal } from '@/context/SellOutProvider';

export default function Home() {
	const { sellOutModalOpen, openSellOutModal } = useSelloutModal();
	console.log(sellOutModalOpen);
	return (
		<div className={''}>
			<Head>
				<title>Create-Web3 App</title>
				<meta name="description" content="Generated by npx create-web3" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<header style={{ padding: '1rem' }}>
				<ConnectButton />
			</header>

			<main
				style={{
					minHeight: '60vh',
					flex: '1',
					display: 'flex',
					flexDirection: 'column',
					justifyContent: 'center',
					alignItems: 'center',
				}}
			>
				<button onClick={openSellOutModal}>Open Sellout modal</button>
				{/* <SellOutCheckOut
					itemMetaData={{
						title: "Nike Men's Joyride Run Flyknit Shoes",
						description: '',
						image:
							'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1625&q=80',
						price: 120,
					}}
				/> */}
			</main>
		</div>
	);
}
