import Head from 'next/head';

import { ConnectButton } from '@rainbow-me/rainbowkit';
import { GetGreeter, SetGreeter } from '../components/contract';
import SellOutCheckOut from '@/components/SellOutCheckOut/SellOutCheckOut';
import { useSelloutModal } from '@/context/SellOutProvider';
import CheckoutModal from '@/components/SellOutCheckOut/CheckoutModal';
import { useState } from 'react';

export default function Home() {
	const { sellOutModalOpen, openSellOutModal, closeModal } = useSelloutModal();
	const [checkOutData, setCheckOutData] = useState<any>(null);

	return (
		<div className={''}>
			<Head>
				<title>Create-Web3 App</title>
				<meta name="description" content="Generated by npx create-web3" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<header style={{ padding: '1rem' }}>
				<ConnectButton />
			</header>

			<main
				style={{
					minHeight: '60vh',
					flex: '1',
					display: 'flex',
					flexDirection: 'column',
					justifyContent: 'center',
					alignItems: 'center',
				}}
			>
				{/* <button onClick={openSellOutModal}>Open Sellout modal</button> */}
				{sellOutModalOpen && checkOutData && (
					<CheckoutModal data={checkOutData} open={sellOutModalOpen} onClose={closeModal} />
				)}
				<div className="grid grid-cols-4 gap-10 w-3/4 mt-10">
					{Array.from({ length: 10 }).map((_, i) => (
						<div onClick={() => setCheckOutData({ title: `Hello World ${i}` })}>
							<MarketCard data={i} />
						</div>
					))}
				</div>
			</main>
		</div>
	);
}

function MarketCard({ data }) {
	const { sellOutModalOpen, openSellOutModal, closeModal } = useSelloutModal();
	return (
		<div onClick={openSellOutModal} className="w-48 h-48 flex border  items-center justify-center">
			<h1>Market Card</h1>
		</div>
	);
}
