import Head from 'next/head';

import { ConnectButton } from '@rainbow-me/rainbowkit';
import { GetGreeter, SetGreeter } from '../components/contract';
import SellOutCheckOut from '@/components/SellOutCheckOut/SellOutCheckOut';
import { useSelloutModal } from '@/context/SellOutProvider';
import CheckoutModal from '@/components/SellOutCheckOut/CheckoutModal';
import { useState } from 'react';
import { Box } from '@/components/SellOutCheckOut/Box';
import { touchableStyles } from '@/styles/css/touchableStyles';
import { generateMockData, MockData } from '@/utils/generateMockData';
import Header from '@/components/Header';

export default function Home() {
	const { sellOutModalOpen, openSellOutModal, closeModal } = useSelloutModal();
	const [checkOutData, setCheckOutData] = useState<any>(null);

	return (
		<div className={''}>
			<Head>
				<title>Create-Web3 App</title>
				<meta name="description" content="Generated by npx create-web3" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />

			<main
				className=""
				style={{
					minHeight: '60vh',
					flex: '1',
					display: 'flex',
					flexDirection: 'column',
					justifyContent: 'center',
					alignItems: 'center',
				}}
			>
				{/* <button onClick={openSellOutModal}>Open Sellout modal</button> */}
				{sellOutModalOpen && checkOutData && (
					<CheckoutModal
						address={false}
						promoCode={false}
						data={checkOutData}
						open={sellOutModalOpen}
						onClose={closeModal}
					/>
				)}
				<div className="grid md:grid-cols-3 grid-cols-1 mt-10 w-[80%]  ">
					{generateMockData().map((data, i) => (
						<div>
							<MarketCard data={data} setCheckOutData={setCheckOutData} />
						</div>
					))}
				</div>
			</main>
		</div>
	);
}

export function MarketCard({ data, setCheckOutData }: { data: MockData; setCheckOutData: (data: any) => void }) {
	const { sellOutModalOpen, openSellOutModal, closeModal } = useSelloutModal();
	return (
		<div className="w-60 rounded overflow-hidden border pt-5 shadow-lg px-5 ">
			<img className="w-full" src={data.image} alt="Sunset in the mountains" />
			<div className="px-2 py-2  flex flex-row">
				<div className="font-bold flex flex-1  items-center   text-sm mb-2">{data.name}</div>
				<div className=" py-2  pb-2 flex justify-end ">
					<div
						className="border cursor-pointer px-4 py-2"
						onClick={(e) => {
							e.stopPropagation();
							setCheckOutData(data);
							openSellOutModal();
						}}
					>
						Buy
					</div>
				</div>
			</div>
		</div>
	);
}
