import Header from '@/components/Header';
import Head from 'next/head';

export default function ComponentExamples() {
	return (
		<div className={''}>
			<Head>
				<title>Create-Web3 App</title>
				<meta name="description" content="Generated by npx create-web3" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />

			<main
				style={{
					minHeight: '60vh',
					flex: '1',
					display: 'flex',
					// flexDirection: 'row',
					justifyContent: 'center',
					alignItems: 'center',
				}}
				className="flex md:flex-row flex-col"
			>
				<div className=" flex flex-1 h-full md:justify-end justify-center mr-5">
					<img src="/ModalComponent.png" className="w-[80%] rounded-lg" />
				</div>
				<div className=" flex flex-1 h-full justify-center md:justify-start ">
					<img src="/SelloutProvider.png" className="w-[70%] rounded-lg" />
				</div>
			</main>
		</div>
	);
}
